#!/usr/bin/env python3
"""
generate_report.py
Generates a single-page SOC investigation PDF for portfolio/demo use.
"""

import time
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Preformatted
from reportlab.platypus.flowables import HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor

def generate_pdf_report(filename="Investigation_PowerShell.pdf"):
    doc = SimpleDocTemplate(
        filename,
        pagesize=A4,
        rightMargin=40, leftMargin=40,
        topMargin=40, bottomMargin=40
    )

    styles = getSampleStyleSheet()
    Story = []

    title_style = ParagraphStyle('CustomTitle', parent=styles['Heading1'], fontSize=14, spaceAfter=8, textColor=HexColor('#003366'))
    header_style = ParagraphStyle('CustomHeader', parent=styles['Heading2'], fontSize=11, spaceAfter=6, spaceBefore=8, textColor=HexColor('#003366'))
    normal_style = ParagraphStyle('Normal', parent=styles['Normal'], fontSize=10, leading=12)
    code_style = ParagraphStyle('CodeStyle', parent=styles['Code'], fontSize=9, leading=11, backColor=HexColor('#f4f4f4'), leftIndent=6, rightIndent=6)

    Story.append(Paragraph("SECURITY INVESTIGATION NOTE", title_style))
    Story.append(Paragraph("Ref: LAB-INV-2026-004  |  Date: 2026-07-20  |  Analyst: L. Barros", normal_style))
    Story.append(Spacer(1, 8))
    Story.append(HRFlowable(width="100%", thickness=1, color=HexColor('#cccccc')))
    Story.append(Spacer(1, 8))

    Story.append(Paragraph("1. ALERT SUMMARY", header_style))
    Story.append(Paragraph("<b>Alert Title:</b> Suspicious Process Execution - Encoded PowerShell Spawned by IIS Process", normal_style))
    Story.append(Paragraph("<b>Severity:</b> High  |  <b>Host:</b> WEB-SRV-01 (lab)  |  <b>Account:</b> svc-webapp", normal_style))
    Story.append(Spacer(1, 8))

    Story.append(Paragraph("2. KQL DETECTION QUERY", header_style))
    kql_query = (
        "DeviceProcessEvents\n"
        "| where Timestamp > ago(12h) and DeviceName == 'WEB-SRV-01'\n"
        "| where InitiatingProcessFileName == 'w3wp.exe' and FileName == 'powershell.exe'\n"
        "| project Timestamp, DeviceName, AccountName, ProcessId, CommandLine, InitiatingProcessCommandLine"
    )
    Story.append(Preformatted(kql_query, code_style))
    Story.append(Spacer(1, 8))

    Story.append(Paragraph("3. INCIDENT TIMELINE (UTC)", header_style))
    timeline = [
        "<b>14:02:11</b> - Inbound web request to /contact/upload.aspx handled by IIS (w3wp.exe).",
        "<b>14:02:15</b> - w3wp.exe (PID 2104) spawns powershell.exe (PID 4892) under svc-webapp.",
        "<b>14:02:16</b> - PowerShell executes encoded command string: powershell.exe -EncodedCommand ...",
        "<b>14:02:18</b> - Encoded payload decodes to script executing whoami /priv.",
        "<b>14:03:00</b> - High-severity alert generated in Defender for Endpoint."
    ]
    for event in timeline:
        Story.append(Paragraph(f"• {event}", normal_style))
    Story.append(Spacer(1, 8))

    Story.append(Paragraph("4. EVIDENCE & CONCLUSION", header_style))
    Story.append(Paragraph("<b>Unusual Parent-Child Relationship:</b> Web servers should not spawn interactive shells.", normal_style))
    Story.append(Paragraph("<b>Command Obfuscation:</b> Use of -EncodedCommand indicates evasion attempt.", normal_style))
    Story.append(Spacer(1, 6))
    Story.append(Paragraph("<b>Likely Cause:</b> Potential file upload abuse allowing unauthorized command execution.", normal_style))
    Story.append(Spacer(1, 8))

    Story.append(Paragraph("5. RECOMMENDED ACTIONS & MITRE ATT&CK", header_style))
    Story.append(Paragraph("1. Perform soft network isolation on WEB-SRV-01 via Defender for Endpoint.", normal_style))
    Story.append(Paragraph("2. Reset credentials for the svc-webapp account and revoke active sessions.", normal_style))
    Story.append(Paragraph("3. Coordinate with the web application team to inspect upload logs and patch the endpoint.", normal_style))
    Story.append(Spacer(1, 6))
    Story.append(Paragraph("<b>MITRE Mapping:</b> T1190 | T1059.001 | T1027 | T1033", normal_style))

    Story.append(Spacer(1, 12))
    footer_style = ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=HexColor('#666666'))
    Story.append(Paragraph("Generated by generate_report.py for portfolio/demo use. Not for production forensic use.", footer_style))

    doc.build(Story)
    print(f"[*] Successfully generated report: {filename}")

if __name__ == "__main__":
    output_file = "Investigation_PowerShell.pdf"
    print("[*] Parsing incident data and generating PDF...")
    time.sleep(1)
    generate_pdf_report(output_file)
